/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_COMM_REVOKE( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke__( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke_( MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_COMM_REVOKE = PMPIX_COMM_REVOKE
#pragma weak mpix_comm_revoke__ = PMPIX_COMM_REVOKE
#pragma weak mpix_comm_revoke_ = PMPIX_COMM_REVOKE
#pragma weak mpix_comm_revoke = PMPIX_COMM_REVOKE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_COMM_REVOKE = pmpix_comm_revoke__
#pragma weak mpix_comm_revoke__ = pmpix_comm_revoke__
#pragma weak mpix_comm_revoke_ = pmpix_comm_revoke__
#pragma weak mpix_comm_revoke = pmpix_comm_revoke__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_COMM_REVOKE = pmpix_comm_revoke_
#pragma weak mpix_comm_revoke__ = pmpix_comm_revoke_
#pragma weak mpix_comm_revoke_ = pmpix_comm_revoke_
#pragma weak mpix_comm_revoke = pmpix_comm_revoke_
#else
#pragma weak MPIX_COMM_REVOKE = pmpix_comm_revoke
#pragma weak mpix_comm_revoke__ = pmpix_comm_revoke
#pragma weak mpix_comm_revoke_ = pmpix_comm_revoke
#pragma weak mpix_comm_revoke = pmpix_comm_revoke
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_COMM_REVOKE( MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_COMM_REVOKE = PMPIX_COMM_REVOKE
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke__( MPI_Fint *, MPI_Fint * );

#pragma weak mpix_comm_revoke__ = pmpix_comm_revoke__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke( MPI_Fint *, MPI_Fint * );

#pragma weak mpix_comm_revoke = pmpix_comm_revoke
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke_( MPI_Fint *, MPI_Fint * );

#pragma weak mpix_comm_revoke_ = pmpix_comm_revoke_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_COMM_REVOKE  MPIX_COMM_REVOKE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_comm_revoke__  mpix_comm_revoke__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_comm_revoke  mpix_comm_revoke
#else
#pragma _HP_SECONDARY_DEF pmpix_comm_revoke_  mpix_comm_revoke_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_COMM_REVOKE as PMPIX_COMM_REVOKE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_comm_revoke__ as pmpix_comm_revoke__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_comm_revoke as pmpix_comm_revoke
#else
#pragma _CRI duplicate mpix_comm_revoke_ as pmpix_comm_revoke_
#endif

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_COMM_REVOKE( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPIX_COMM_REVOKE")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPIX_COMM_REVOKE")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPIX_COMM_REVOKE")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPIX_COMM_REVOKE")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPIX_COMM_REVOKE( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke__")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke__")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke__")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPIX_COMM_REVOKE( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke_")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke_")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke_")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPIX_COMM_REVOKE( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke")));

#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(USE_ONLY_MPI_NAMES)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_COMM_REVOKE( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke__( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke_( MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_comm_revoke__ = MPIX_COMM_REVOKE
#pragma weak mpix_comm_revoke_ = MPIX_COMM_REVOKE
#pragma weak mpix_comm_revoke = MPIX_COMM_REVOKE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_COMM_REVOKE = mpix_comm_revoke__
#pragma weak mpix_comm_revoke_ = mpix_comm_revoke__
#pragma weak mpix_comm_revoke = mpix_comm_revoke__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_COMM_REVOKE = mpix_comm_revoke_
#pragma weak mpix_comm_revoke__ = mpix_comm_revoke_
#pragma weak mpix_comm_revoke = mpix_comm_revoke_
#else
#pragma weak MPIX_COMM_REVOKE = mpix_comm_revoke
#pragma weak mpix_comm_revoke__ = mpix_comm_revoke
#pragma weak mpix_comm_revoke_ = mpix_comm_revoke
#endif
#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_COMM_REVOKE( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPIX_COMM_REVOKE")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPIX_COMM_REVOKE")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPIX_COMM_REVOKE")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPIX_COMM_REVOKE( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_comm_revoke__")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke__( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_comm_revoke__")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_comm_revoke__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPIX_COMM_REVOKE( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_comm_revoke_")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_comm_revoke_")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke_( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_comm_revoke_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPIX_COMM_REVOKE( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_comm_revoke")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_comm_revoke")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_comm_revoke")));
extern FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke( MPI_Fint *, MPI_Fint * );

#endif
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_COMM_REVOKE( MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_comm_revoke__( MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_comm_revoke_( MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_comm_revoke( MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_comm_revoke__ = PMPIX_COMM_REVOKE
#pragma weak pmpix_comm_revoke_ = PMPIX_COMM_REVOKE
#pragma weak pmpix_comm_revoke = PMPIX_COMM_REVOKE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_COMM_REVOKE = pmpix_comm_revoke__
#pragma weak pmpix_comm_revoke_ = pmpix_comm_revoke__
#pragma weak pmpix_comm_revoke = pmpix_comm_revoke__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_COMM_REVOKE = pmpix_comm_revoke_
#pragma weak pmpix_comm_revoke__ = pmpix_comm_revoke_
#pragma weak pmpix_comm_revoke = pmpix_comm_revoke_
#else
#pragma weak PMPIX_COMM_REVOKE = pmpix_comm_revoke
#pragma weak pmpix_comm_revoke__ = pmpix_comm_revoke
#pragma weak pmpix_comm_revoke_ = pmpix_comm_revoke
#endif /* Test on name mapping */

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL pmpix_comm_revoke__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPIX_COMM_REVOKE")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_comm_revoke_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPIX_COMM_REVOKE")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_comm_revoke( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPIX_COMM_REVOKE")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPIX_COMM_REVOKE( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke__")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_comm_revoke_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke__")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_comm_revoke( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPIX_COMM_REVOKE( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke_")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_comm_revoke__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke_")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_comm_revoke( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke_")));

#else
extern FORT_DLL_SPEC void FORT_CALL PMPIX_COMM_REVOKE( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_comm_revoke__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_comm_revoke_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_comm_revoke")));

#endif /* Test on name mapping */
#endif /* HAVE_MULTIPLE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */

#ifdef F77_NAME_UPPER
#define mpix_comm_revoke_ PMPIX_COMM_REVOKE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_comm_revoke_ pmpix_comm_revoke__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_comm_revoke_ pmpix_comm_revoke
#else
#define mpix_comm_revoke_ pmpix_comm_revoke_
#endif /* Test on name mapping */

#ifdef F77_USE_PMPI
/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Comm_revoke
#define MPIX_Comm_revoke PMPIX_Comm_revoke 
#endif

#else

#ifdef F77_NAME_UPPER
#define mpix_comm_revoke_ MPIX_COMM_REVOKE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_comm_revoke_ mpix_comm_revoke__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_comm_revoke_ mpix_comm_revoke
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_comm_revoke_ ( MPI_Fint *v1, MPI_Fint *ierr ){
    *ierr = MPIX_Comm_revoke( (MPI_Comm)(*v1) );
}
