/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_RANK( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank__( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank_( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPI_GROUP_RANK = PMPI_GROUP_RANK
#pragma weak mpi_group_rank__ = PMPI_GROUP_RANK
#pragma weak mpi_group_rank_ = PMPI_GROUP_RANK
#pragma weak mpi_group_rank = PMPI_GROUP_RANK
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_GROUP_RANK = pmpi_group_rank__
#pragma weak mpi_group_rank__ = pmpi_group_rank__
#pragma weak mpi_group_rank_ = pmpi_group_rank__
#pragma weak mpi_group_rank = pmpi_group_rank__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_GROUP_RANK = pmpi_group_rank_
#pragma weak mpi_group_rank__ = pmpi_group_rank_
#pragma weak mpi_group_rank_ = pmpi_group_rank_
#pragma weak mpi_group_rank = pmpi_group_rank_
#else
#pragma weak MPI_GROUP_RANK = pmpi_group_rank
#pragma weak mpi_group_rank__ = pmpi_group_rank
#pragma weak mpi_group_rank_ = pmpi_group_rank
#pragma weak mpi_group_rank = pmpi_group_rank
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_RANK( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPI_GROUP_RANK = PMPI_GROUP_RANK
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank__( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_group_rank__ = pmpi_group_rank__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_group_rank = pmpi_group_rank
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank_( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_group_rank_ = pmpi_group_rank_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_GROUP_RANK  MPI_GROUP_RANK
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_group_rank__  mpi_group_rank__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_group_rank  mpi_group_rank
#else
#pragma _HP_SECONDARY_DEF pmpi_group_rank_  mpi_group_rank_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_GROUP_RANK as PMPI_GROUP_RANK
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_group_rank__ as pmpi_group_rank__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_group_rank as pmpi_group_rank
#else
#pragma _CRI duplicate mpi_group_rank_ as pmpi_group_rank_
#endif

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_RANK( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_GROUP_RANK")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_GROUP_RANK")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_GROUP_RANK")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_GROUP_RANK")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_RANK( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_RANK( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_RANK( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank")));

#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(USE_ONLY_MPI_NAMES)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_RANK( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank__( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank_( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpi_group_rank__ = MPI_GROUP_RANK
#pragma weak mpi_group_rank_ = MPI_GROUP_RANK
#pragma weak mpi_group_rank = MPI_GROUP_RANK
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_GROUP_RANK = mpi_group_rank__
#pragma weak mpi_group_rank_ = mpi_group_rank__
#pragma weak mpi_group_rank = mpi_group_rank__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_GROUP_RANK = mpi_group_rank_
#pragma weak mpi_group_rank__ = mpi_group_rank_
#pragma weak mpi_group_rank = mpi_group_rank_
#else
#pragma weak MPI_GROUP_RANK = mpi_group_rank
#pragma weak mpi_group_rank__ = mpi_group_rank
#pragma weak mpi_group_rank_ = mpi_group_rank
#endif
#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_RANK( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_GROUP_RANK")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_GROUP_RANK")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_GROUP_RANK")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_RANK( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_group_rank__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank__( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_group_rank__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_group_rank__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_RANK( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_group_rank_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_group_rank_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank_( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_group_rank_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_RANK( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_group_rank")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_group_rank")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_group_rank")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_rank( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPI_GROUP_RANK( MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_rank__( MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_rank_( MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_rank( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpi_group_rank__ = PMPI_GROUP_RANK
#pragma weak pmpi_group_rank_ = PMPI_GROUP_RANK
#pragma weak pmpi_group_rank = PMPI_GROUP_RANK
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPI_GROUP_RANK = pmpi_group_rank__
#pragma weak pmpi_group_rank_ = pmpi_group_rank__
#pragma weak pmpi_group_rank = pmpi_group_rank__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPI_GROUP_RANK = pmpi_group_rank_
#pragma weak pmpi_group_rank__ = pmpi_group_rank_
#pragma weak pmpi_group_rank = pmpi_group_rank_
#else
#pragma weak PMPI_GROUP_RANK = pmpi_group_rank
#pragma weak pmpi_group_rank__ = pmpi_group_rank
#pragma weak pmpi_group_rank_ = pmpi_group_rank
#endif /* Test on name mapping */

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_rank__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_GROUP_RANK")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_rank_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_GROUP_RANK")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_rank( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_GROUP_RANK")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_GROUP_RANK( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_rank_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_rank( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_GROUP_RANK( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_rank__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_rank( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank_")));

#else
extern FORT_DLL_SPEC void FORT_CALL PMPI_GROUP_RANK( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_rank__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_rank_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_group_rank")));

#endif /* Test on name mapping */
#endif /* HAVE_MULTIPLE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */

#ifdef F77_NAME_UPPER
#define mpi_group_rank_ PMPI_GROUP_RANK
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_group_rank_ pmpi_group_rank__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_group_rank_ pmpi_group_rank
#else
#define mpi_group_rank_ pmpi_group_rank_
#endif /* Test on name mapping */

#ifdef F77_USE_PMPI
/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPI_Group_rank
#define MPI_Group_rank PMPI_Group_rank 
#endif

#else

#ifdef F77_NAME_UPPER
#define mpi_group_rank_ MPI_GROUP_RANK
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_group_rank_ mpi_group_rank__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_group_rank_ mpi_group_rank
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpi_group_rank_ ( MPI_Fint *v1, MPI_Fint *v2, MPI_Fint *ierr ){
    *ierr = MPI_Group_rank( (MPI_Group)*v1, v2 );
}
