/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_TRANSLATE_RANKS( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks__( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks_( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPI_GROUP_TRANSLATE_RANKS = PMPI_GROUP_TRANSLATE_RANKS
#pragma weak mpi_group_translate_ranks__ = PMPI_GROUP_TRANSLATE_RANKS
#pragma weak mpi_group_translate_ranks_ = PMPI_GROUP_TRANSLATE_RANKS
#pragma weak mpi_group_translate_ranks = PMPI_GROUP_TRANSLATE_RANKS
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_GROUP_TRANSLATE_RANKS = pmpi_group_translate_ranks__
#pragma weak mpi_group_translate_ranks__ = pmpi_group_translate_ranks__
#pragma weak mpi_group_translate_ranks_ = pmpi_group_translate_ranks__
#pragma weak mpi_group_translate_ranks = pmpi_group_translate_ranks__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_GROUP_TRANSLATE_RANKS = pmpi_group_translate_ranks_
#pragma weak mpi_group_translate_ranks__ = pmpi_group_translate_ranks_
#pragma weak mpi_group_translate_ranks_ = pmpi_group_translate_ranks_
#pragma weak mpi_group_translate_ranks = pmpi_group_translate_ranks_
#else
#pragma weak MPI_GROUP_TRANSLATE_RANKS = pmpi_group_translate_ranks
#pragma weak mpi_group_translate_ranks__ = pmpi_group_translate_ranks
#pragma weak mpi_group_translate_ranks_ = pmpi_group_translate_ranks
#pragma weak mpi_group_translate_ranks = pmpi_group_translate_ranks
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_TRANSLATE_RANKS( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );

#pragma weak MPI_GROUP_TRANSLATE_RANKS = PMPI_GROUP_TRANSLATE_RANKS
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks__( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );

#pragma weak mpi_group_translate_ranks__ = pmpi_group_translate_ranks__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );

#pragma weak mpi_group_translate_ranks = pmpi_group_translate_ranks
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks_( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );

#pragma weak mpi_group_translate_ranks_ = pmpi_group_translate_ranks_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_GROUP_TRANSLATE_RANKS  MPI_GROUP_TRANSLATE_RANKS
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_group_translate_ranks__  mpi_group_translate_ranks__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_group_translate_ranks  mpi_group_translate_ranks
#else
#pragma _HP_SECONDARY_DEF pmpi_group_translate_ranks_  mpi_group_translate_ranks_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_GROUP_TRANSLATE_RANKS as PMPI_GROUP_TRANSLATE_RANKS
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_group_translate_ranks__ as pmpi_group_translate_ranks__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_group_translate_ranks as pmpi_group_translate_ranks
#else
#pragma _CRI duplicate mpi_group_translate_ranks_ as pmpi_group_translate_ranks_
#endif

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_TRANSLATE_RANKS( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("PMPI_GROUP_TRANSLATE_RANKS")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks__( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("PMPI_GROUP_TRANSLATE_RANKS")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks_( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("PMPI_GROUP_TRANSLATE_RANKS")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("PMPI_GROUP_TRANSLATE_RANKS")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_TRANSLATE_RANKS( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks__( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks_( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_TRANSLATE_RANKS( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks__( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks_( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_TRANSLATE_RANKS( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks__( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks_( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks")));

#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(USE_ONLY_MPI_NAMES)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_TRANSLATE_RANKS( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks__( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks_( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpi_group_translate_ranks__ = MPI_GROUP_TRANSLATE_RANKS
#pragma weak mpi_group_translate_ranks_ = MPI_GROUP_TRANSLATE_RANKS
#pragma weak mpi_group_translate_ranks = MPI_GROUP_TRANSLATE_RANKS
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_GROUP_TRANSLATE_RANKS = mpi_group_translate_ranks__
#pragma weak mpi_group_translate_ranks_ = mpi_group_translate_ranks__
#pragma weak mpi_group_translate_ranks = mpi_group_translate_ranks__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_GROUP_TRANSLATE_RANKS = mpi_group_translate_ranks_
#pragma weak mpi_group_translate_ranks__ = mpi_group_translate_ranks_
#pragma weak mpi_group_translate_ranks = mpi_group_translate_ranks_
#else
#pragma weak MPI_GROUP_TRANSLATE_RANKS = mpi_group_translate_ranks
#pragma weak mpi_group_translate_ranks__ = mpi_group_translate_ranks
#pragma weak mpi_group_translate_ranks_ = mpi_group_translate_ranks
#endif
#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_TRANSLATE_RANKS( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks__( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("MPI_GROUP_TRANSLATE_RANKS")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks_( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("MPI_GROUP_TRANSLATE_RANKS")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("MPI_GROUP_TRANSLATE_RANKS")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_TRANSLATE_RANKS( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("mpi_group_translate_ranks__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks__( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks_( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("mpi_group_translate_ranks__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("mpi_group_translate_ranks__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_TRANSLATE_RANKS( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("mpi_group_translate_ranks_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks__( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("mpi_group_translate_ranks_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks_( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("mpi_group_translate_ranks_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_GROUP_TRANSLATE_RANKS( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("mpi_group_translate_ranks")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks__( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("mpi_group_translate_ranks")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks_( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("mpi_group_translate_ranks")));
extern FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );

#endif
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPI_GROUP_TRANSLATE_RANKS( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_translate_ranks__( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_translate_ranks_( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_translate_ranks( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpi_group_translate_ranks__ = PMPI_GROUP_TRANSLATE_RANKS
#pragma weak pmpi_group_translate_ranks_ = PMPI_GROUP_TRANSLATE_RANKS
#pragma weak pmpi_group_translate_ranks = PMPI_GROUP_TRANSLATE_RANKS
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPI_GROUP_TRANSLATE_RANKS = pmpi_group_translate_ranks__
#pragma weak pmpi_group_translate_ranks_ = pmpi_group_translate_ranks__
#pragma weak pmpi_group_translate_ranks = pmpi_group_translate_ranks__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPI_GROUP_TRANSLATE_RANKS = pmpi_group_translate_ranks_
#pragma weak pmpi_group_translate_ranks__ = pmpi_group_translate_ranks_
#pragma weak pmpi_group_translate_ranks = pmpi_group_translate_ranks_
#else
#pragma weak PMPI_GROUP_TRANSLATE_RANKS = pmpi_group_translate_ranks
#pragma weak pmpi_group_translate_ranks__ = pmpi_group_translate_ranks
#pragma weak pmpi_group_translate_ranks_ = pmpi_group_translate_ranks
#endif /* Test on name mapping */

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_translate_ranks__( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("PMPI_GROUP_TRANSLATE_RANKS")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_translate_ranks_( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("PMPI_GROUP_TRANSLATE_RANKS")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_translate_ranks( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("PMPI_GROUP_TRANSLATE_RANKS")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_GROUP_TRANSLATE_RANKS( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_translate_ranks_( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_translate_ranks( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_GROUP_TRANSLATE_RANKS( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_translate_ranks__( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_translate_ranks( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks_")));

#else
extern FORT_DLL_SPEC void FORT_CALL PMPI_GROUP_TRANSLATE_RANKS( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_translate_ranks__( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_group_translate_ranks_( MPI_Fint *, MPI_Fint *, MPI_Fint [], MPI_Fint *, MPI_Fint [], MPI_Fint * ) __attribute__((weak,alias("pmpi_group_translate_ranks")));

#endif /* Test on name mapping */
#endif /* HAVE_MULTIPLE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */

#ifdef F77_NAME_UPPER
#define mpi_group_translate_ranks_ PMPI_GROUP_TRANSLATE_RANKS
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_group_translate_ranks_ pmpi_group_translate_ranks__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_group_translate_ranks_ pmpi_group_translate_ranks
#else
#define mpi_group_translate_ranks_ pmpi_group_translate_ranks_
#endif /* Test on name mapping */

#ifdef F77_USE_PMPI
/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPI_Group_translate_ranks
#define MPI_Group_translate_ranks PMPI_Group_translate_ranks 
#endif

#else

#ifdef F77_NAME_UPPER
#define mpi_group_translate_ranks_ MPI_GROUP_TRANSLATE_RANKS
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_group_translate_ranks_ mpi_group_translate_ranks__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_group_translate_ranks_ mpi_group_translate_ranks
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpi_group_translate_ranks_ ( MPI_Fint *v1, MPI_Fint *v2, MPI_Fint v3[], MPI_Fint *v4, MPI_Fint v5[], MPI_Fint *ierr ){
    *ierr = MPI_Group_translate_ranks( (MPI_Group)*v1, (int)*v2, v3, (MPI_Group)*v4, v5 );
}
