.TH hydra_nameserver 1 "11/9/2015" " " "HYDRA"
.SH NAME
hydra_nameserver \-  Internal executable used by Hydra 
.SH DESCRIPTION
This executable is designed to not be run directly by users, but to
support the Hydra process manager. As such, no documentation will be
provided here.

.SH LOCATION
/tmp/wB2927n3sW/mpich-3.2/src/pm/hydra/tools/nameserver/hydra_nameserver.txt
