C_source := uart.c timer.c tasks.c signal.c #irq.c idt.c isrs.c gdt.c processor.c timer.c tasks.c apic.c pci.c vga.c uart.c syscall.c
ASM_source := entry.S
MODULE := arch_arm64_kernel

include $(TOPDIR)/Makefile.inc
